// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```  
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASP4otHl9o6x15GJ4peHugMlCMcjtgCPA',
    appId: '1:424594905851:web:ed201fa7243269754fee5e',
    messagingSenderId: '424594905851',
    projectId: 'hella-dcea7',
    authDomain: 'hella-dcea7.firebaseapp.com',
    storageBucket: 'hella-dcea7.firebasestorage.app',
    measurementId: 'G-CHM8SGT0DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWfA0Ao5A59uVH7u7PyMieJgmZlIfJkKM',
    appId: '1:424594905851:android:0b17341bd0b72f9c4fee5e',
    messagingSenderId: '424594905851',
    projectId: 'hella-dcea7',
    storageBucket: 'hella-dcea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCirzA5Ax2atFTUKPVXJpDNIXA3JMb-3yA',
    appId: '1:424594905851:ios:8bb7258e96708c944fee5e',
    messagingSenderId: '424594905851',
    projectId: 'hella-dcea7',
    storageBucket: 'hella-dcea7.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCirzA5Ax2atFTUKPVXJpDNIXA3JMb-3yA',
    appId: '1:424594905851:ios:8bb7258e96708c944fee5e',
    messagingSenderId: '424594905851',
    projectId: 'hella-dcea7',
    storageBucket: 'hella-dcea7.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASP4otHl9o6x15GJ4peHugMlCMcjtgCPA',
    appId: '1:424594905851:web:49e493415e9567ac4fee5e',
    messagingSenderId: '424594905851',
    projectId: 'hella-dcea7',
    authDomain: 'hella-dcea7.firebaseapp.com',
    storageBucket: 'hella-dcea7.firebasestorage.app',
    measurementId: 'G-JRML1JMYYZ',
  );
}
